/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceEnterpriseType;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceEnterpriseTypePosition;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServicePrefectureCode;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceUrlType;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AccountManagementServiceClientオブジェクトは、広告主情報を表します。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AccountManagementServiceClient object describes the client information.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">AccountManagementServiceClientオブジェクトは、広告主情報を表します。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。</div> <div lang=\"en\">AccountManagementServiceClient object describes the client information.<br> This field is required in ADD operation, and will be ignored in SET operation.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class AccountManagementServiceClient {
  public static final String SERIALIZED_NAME_BUILDING = "building";
  @SerializedName(SERIALIZED_NAME_BUILDING)
  private String building;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_CLIENT_PERSON_NAME = "clientPersonName";
  @SerializedName(SERIALIZED_NAME_CLIENT_PERSON_NAME)
  private String clientPersonName;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_COMPANY_NAME_KANA = "companyNameKana";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME_KANA)
  private String companyNameKana;

  public static final String SERIALIZED_NAME_ENTERPRISE_TYPE = "enterpriseType";
  @SerializedName(SERIALIZED_NAME_ENTERPRISE_TYPE)
  private AccountManagementServiceEnterpriseType enterpriseType;

  public static final String SERIALIZED_NAME_ENTERPRISE_TYPE_POSITION = "enterpriseTypePosition";
  @SerializedName(SERIALIZED_NAME_ENTERPRISE_TYPE_POSITION)
  private AccountManagementServiceEnterpriseTypePosition enterpriseTypePosition;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_PREFECTURE_CODE = "prefectureCode";
  @SerializedName(SERIALIZED_NAME_PREFECTURE_CODE)
  private AccountManagementServicePrefectureCode prefectureCode;

  public static final String SERIALIZED_NAME_STREET1 = "street1";
  @SerializedName(SERIALIZED_NAME_STREET1)
  private String street1;

  public static final String SERIALIZED_NAME_STREET2 = "street2";
  @SerializedName(SERIALIZED_NAME_STREET2)
  private String street2;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_URL_TYPE = "urlType";
  @SerializedName(SERIALIZED_NAME_URL_TYPE)
  private AccountManagementServiceUrlType urlType;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;


  public AccountManagementServiceClient building(String building) {
    
    this.building = building;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ビル名です。&lt;br&gt;このフィールドは、ADD時に省略可能となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Building name.&lt;br&gt;This field is optional in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return building
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ビル名です。<br>このフィールドは、ADD時に省略可能となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Building name.<br>This field is optional in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getBuilding() {
    return building;
  }


  public void setBuilding(String building) {
    this.building = building;
  }


  public AccountManagementServiceClient city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;市区町村名です。&lt;br&gt;このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;City name.&lt;br&gt;This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">市区町村名です。<br>このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">City name.<br>This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public AccountManagementServiceClient clientPersonName(String clientPersonName) {
    
    this.clientPersonName = clientPersonName;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告主の担当者氏名です。&lt;br&gt; このフィールドは、ADD時に省略可能となり、SET時に無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Client person name.&lt;br&gt; This field is optional in ADD operation, and will be ignored in SET operation.&lt;/div&gt; 
   * @return clientPersonName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告主の担当者氏名です。<br> このフィールドは、ADD時に省略可能となり、SET時に無視されます。</div> <div lang=\"en\">Client person name.<br> This field is optional in ADD operation, and will be ignored in SET operation.</div> ")

  public String getClientPersonName() {
    return clientPersonName;
  }


  public void setClientPersonName(String clientPersonName) {
    this.clientPersonName = clientPersonName;
  }


  public AccountManagementServiceClient companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告主名です。&lt;br&gt;このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Company name.&lt;br&gt;This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告主名です。<br>このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Company name.<br>This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public AccountManagementServiceClient companyNameKana(String companyNameKana) {
    
    this.companyNameKana = companyNameKana;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告主名カナです。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Kana characters of company name.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return companyNameKana
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告主名カナです。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Kana characters of company name.<br> This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getCompanyNameKana() {
    return companyNameKana;
  }


  public void setCompanyNameKana(String companyNameKana) {
    this.companyNameKana = companyNameKana;
  }


  public AccountManagementServiceClient enterpriseType(AccountManagementServiceEnterpriseType enterpriseType) {
    
    this.enterpriseType = enterpriseType;
    return this;
  }

   /**
   * Get enterpriseType
   * @return enterpriseType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServiceEnterpriseType getEnterpriseType() {
    return enterpriseType;
  }


  public void setEnterpriseType(AccountManagementServiceEnterpriseType enterpriseType) {
    this.enterpriseType = enterpriseType;
  }


  public AccountManagementServiceClient enterpriseTypePosition(AccountManagementServiceEnterpriseTypePosition enterpriseTypePosition) {
    
    this.enterpriseTypePosition = enterpriseTypePosition;
    return this;
  }

   /**
   * Get enterpriseTypePosition
   * @return enterpriseTypePosition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServiceEnterpriseTypePosition getEnterpriseTypePosition() {
    return enterpriseTypePosition;
  }


  public void setEnterpriseTypePosition(AccountManagementServiceEnterpriseTypePosition enterpriseTypePosition) {
    this.enterpriseTypePosition = enterpriseTypePosition;
  }


  public AccountManagementServiceClient phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;電話番号です。&lt;br&gt; ※xxxxx-xxxxx-xxxxx形式です。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Phone number.&lt;br&gt; * In xxxxx-xxxxx-xxxxx format.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return phoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">電話番号です。<br> ※xxxxx-xxxxx-xxxxx形式です。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Phone number.<br> * In xxxxx-xxxxx-xxxxx format.<br> This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getPhoneNumber() {
    return phoneNumber;
  }


  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public AccountManagementServiceClient prefectureCode(AccountManagementServicePrefectureCode prefectureCode) {
    
    this.prefectureCode = prefectureCode;
    return this;
  }

   /**
   * Get prefectureCode
   * @return prefectureCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServicePrefectureCode getPrefectureCode() {
    return prefectureCode;
  }


  public void setPrefectureCode(AccountManagementServicePrefectureCode prefectureCode) {
    this.prefectureCode = prefectureCode;
  }


  public AccountManagementServiceClient street1(String street1) {
    
    this.street1 = street1;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;町・字名です。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Street1.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return street1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">町・字名です。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Street1.<br> This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getStreet1() {
    return street1;
  }


  public void setStreet1(String street1) {
    this.street1 = street1;
  }


  public AccountManagementServiceClient street2(String street2) {
    
    this.street2 = street2;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;丁目・番地・号です。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Street2.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return street2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">丁目・番地・号です。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Street2.<br> This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getStreet2() {
    return street2;
  }


  public void setStreet2(String street2) {
    this.street2 = street2;
  }


  public AccountManagementServiceClient url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告掲載を希望するサイトのURLです。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Site URL for placing advertisement.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;/div&gt; 
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告掲載を希望するサイトのURLです。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。</div> <div lang=\"en\">Site URL for placing advertisement.<br> This field is required in ADD operation, and will be ignored in SET operation.</div> ")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public AccountManagementServiceClient urlType(AccountManagementServiceUrlType urlType) {
    
    this.urlType = urlType;
    return this;
  }

   /**
   * Get urlType
   * @return urlType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServiceUrlType getUrlType() {
    return urlType;
  }


  public void setUrlType(AccountManagementServiceUrlType urlType) {
    this.urlType = urlType;
  }


  public AccountManagementServiceClient zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;郵便番号です。&lt;br&gt; ※xxx-xxxx形式です。&lt;br&gt; このフィールドは、ADD時に必須となり、SET時に無視されます。&lt;br&gt; ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Zip code.&lt;br&gt; * In xxx-xxxx format.&lt;br&gt; This field is required in ADD operation, and will be ignored in SET operation.&lt;br&gt; * When clientType is \&quot;SELF\&quot;, this field will be ignored in ADD and SET operations.&lt;/div&gt; 
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">郵便番号です。<br> ※xxx-xxxx形式です。<br> このフィールドは、ADD時に必須となり、SET時に無視されます。<br> ※clientTypeがSELFの場合は、ADD時、SET時ともに無視されます。</div> <div lang=\"en\">Zip code.<br> * In xxx-xxxx format.<br> This field is required in ADD operation, and will be ignored in SET operation.<br> * When clientType is \"SELF\", this field will be ignored in ADD and SET operations.</div> ")

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountManagementServiceClient accountManagementServiceClient = (AccountManagementServiceClient) o;
    return Objects.equals(this.building, accountManagementServiceClient.building) &&
        Objects.equals(this.city, accountManagementServiceClient.city) &&
        Objects.equals(this.clientPersonName, accountManagementServiceClient.clientPersonName) &&
        Objects.equals(this.companyName, accountManagementServiceClient.companyName) &&
        Objects.equals(this.companyNameKana, accountManagementServiceClient.companyNameKana) &&
        Objects.equals(this.enterpriseType, accountManagementServiceClient.enterpriseType) &&
        Objects.equals(this.enterpriseTypePosition, accountManagementServiceClient.enterpriseTypePosition) &&
        Objects.equals(this.phoneNumber, accountManagementServiceClient.phoneNumber) &&
        Objects.equals(this.prefectureCode, accountManagementServiceClient.prefectureCode) &&
        Objects.equals(this.street1, accountManagementServiceClient.street1) &&
        Objects.equals(this.street2, accountManagementServiceClient.street2) &&
        Objects.equals(this.url, accountManagementServiceClient.url) &&
        Objects.equals(this.urlType, accountManagementServiceClient.urlType) &&
        Objects.equals(this.zip, accountManagementServiceClient.zip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(building, city, clientPersonName, companyName, companyNameKana, enterpriseType, enterpriseTypePosition, phoneNumber, prefectureCode, street1, street2, url, urlType, zip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountManagementServiceClient {\n");
    sb.append("    building: ").append(toIndentedString(building)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    clientPersonName: ").append(toIndentedString(clientPersonName)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    companyNameKana: ").append(toIndentedString(companyNameKana)).append("\n");
    sb.append("    enterpriseType: ").append(toIndentedString(enterpriseType)).append("\n");
    sb.append("    enterpriseTypePosition: ").append(toIndentedString(enterpriseTypePosition)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    prefectureCode: ").append(toIndentedString(prefectureCode)).append("\n");
    sb.append("    street1: ").append(toIndentedString(street1)).append("\n");
    sb.append("    street2: ").append(toIndentedString(street2)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    urlType: ").append(toIndentedString(urlType)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

