/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceAuthType;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceIncludeTestAccount;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServicePaymentType;
import jp.co.yahoo.adssearchapi.v4.model.AccountManagementServiceStatus;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AccountManagementServiceSelectorオブジェクトは、選択するアカウントを表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AccountManagementServiceSelector object explains which accounts to return.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">AccountManagementServiceSelectorオブジェクトは、選択するアカウントを表します。</div> <div lang=\"en\">AccountManagementServiceSelector object explains which accounts to return.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class AccountManagementServiceSelector {
  public static final String SERIALIZED_NAME_ACCOUNT_IDS = "accountIds";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDS)
  private List<Long> accountIds = null;

  public static final String SERIALIZED_NAME_ACCOUNT_STATUSES = "accountStatuses";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_STATUSES)
  private List<AccountManagementServiceStatus> accountStatuses = null;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPES = "accountTypes";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPES)
  private List<AccountManagementServicePaymentType> accountTypes = null;

  public static final String SERIALIZED_NAME_AUTH_TYPE = "authType";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  private AccountManagementServiceAuthType authType;

  public static final String SERIALIZED_NAME_INCLUDE_TEST_ACCOUNT = "includeTestAccount";
  @SerializedName(SERIALIZED_NAME_INCLUDE_TEST_ACCOUNT)
  private AccountManagementServiceIncludeTestAccount includeTestAccount;

  public static final String SERIALIZED_NAME_NUMBER_RESULTS = "numberResults";
  @SerializedName(SERIALIZED_NAME_NUMBER_RESULTS)
  private Integer numberResults = 200;

  public static final String SERIALIZED_NAME_START_INDEX = "startIndex";
  @SerializedName(SERIALIZED_NAME_START_INDEX)
  private Integer startIndex = 1;


  public AccountManagementServiceSelector accountIds(List<Long> accountIds) {
    
    this.accountIds = accountIds;
    return this;
  }

  public AccountManagementServiceSelector addAccountIdsItem(Long accountIdsItem) {
    if (this.accountIds == null) {
      this.accountIds = new ArrayList<Long>();
    }
    this.accountIds.add(accountIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;検索条件：アカウントID&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account IDs.&lt;/div&gt; 
   * @return accountIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">検索条件：アカウントID</div> <div lang=\"en\">Account IDs.</div> ")

  public List<Long> getAccountIds() {
    return accountIds;
  }


  public void setAccountIds(List<Long> accountIds) {
    this.accountIds = accountIds;
  }


  public AccountManagementServiceSelector accountStatuses(List<AccountManagementServiceStatus> accountStatuses) {
    
    this.accountStatuses = accountStatuses;
    return this;
  }

  public AccountManagementServiceSelector addAccountStatusesItem(AccountManagementServiceStatus accountStatusesItem) {
    if (this.accountStatuses == null) {
      this.accountStatuses = new ArrayList<AccountManagementServiceStatus>();
    }
    this.accountStatuses.add(accountStatusesItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;検索条件：アカウントステータス&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account Statuses.&lt;/div&gt; 
   * @return accountStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">検索条件：アカウントステータス</div> <div lang=\"en\">Account Statuses.</div> ")

  public List<AccountManagementServiceStatus> getAccountStatuses() {
    return accountStatuses;
  }


  public void setAccountStatuses(List<AccountManagementServiceStatus> accountStatuses) {
    this.accountStatuses = accountStatuses;
  }


  public AccountManagementServiceSelector accountTypes(List<AccountManagementServicePaymentType> accountTypes) {
    
    this.accountTypes = accountTypes;
    return this;
  }

  public AccountManagementServiceSelector addAccountTypesItem(AccountManagementServicePaymentType accountTypesItem) {
    if (this.accountTypes == null) {
      this.accountTypes = new ArrayList<AccountManagementServicePaymentType>();
    }
    this.accountTypes.add(accountTypesItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;検索条件：アカウントの料金支払い種別&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account Payment Types.&lt;/div&gt; 
   * @return accountTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">検索条件：アカウントの料金支払い種別</div> <div lang=\"en\">Account Payment Types.</div> ")

  public List<AccountManagementServicePaymentType> getAccountTypes() {
    return accountTypes;
  }


  public void setAccountTypes(List<AccountManagementServicePaymentType> accountTypes) {
    this.accountTypes = accountTypes;
  }


  public AccountManagementServiceSelector authType(AccountManagementServiceAuthType authType) {
    
    this.authType = authType;
    return this;
  }

   /**
   * Get authType
   * @return authType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServiceAuthType getAuthType() {
    return authType;
  }


  public void setAuthType(AccountManagementServiceAuthType authType) {
    this.authType = authType;
  }


  public AccountManagementServiceSelector includeTestAccount(AccountManagementServiceIncludeTestAccount includeTestAccount) {
    
    this.includeTestAccount = includeTestAccount;
    return this;
  }

   /**
   * Get includeTestAccount
   * @return includeTestAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccountManagementServiceIncludeTestAccount getIncludeTestAccount() {
    return includeTestAccount;
  }


  public void setIncludeTestAccount(AccountManagementServiceIncludeTestAccount includeTestAccount) {
    this.includeTestAccount = includeTestAccount;
  }


  public AccountManagementServiceSelector numberResults(Integer numberResults) {
    
    this.numberResults = numberResults;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ページの最大件数です。このフィールドは、1以上を指定する必要があります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Maximum number of results to return in this page. This field must be greater than or equal to 1.&lt;/div&gt; 
   * minimum: 1
   * maximum: 200
   * @return numberResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ページの最大件数です。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Maximum number of results to return in this page. This field must be greater than or equal to 1.</div> ")

  public Integer getNumberResults() {
    return numberResults;
  }


  public void setNumberResults(Integer numberResults) {
    this.numberResults = numberResults;
  }


  public AccountManagementServiceSelector startIndex(Integer startIndex) {
    
    this.startIndex = startIndex;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ページの先頭のインデックスです。このフィールドは、1以上を指定する必要があります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Index of the first result to return in this page. This field must be greater than or equal to 1.&lt;/div&gt; 
   * minimum: 1
   * @return startIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ページの先頭のインデックスです。このフィールドは、1以上を指定する必要があります。</div> <div lang=\"en\">Index of the first result to return in this page. This field must be greater than or equal to 1.</div> ")

  public Integer getStartIndex() {
    return startIndex;
  }


  public void setStartIndex(Integer startIndex) {
    this.startIndex = startIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountManagementServiceSelector accountManagementServiceSelector = (AccountManagementServiceSelector) o;
    return Objects.equals(this.accountIds, accountManagementServiceSelector.accountIds) &&
        Objects.equals(this.accountStatuses, accountManagementServiceSelector.accountStatuses) &&
        Objects.equals(this.accountTypes, accountManagementServiceSelector.accountTypes) &&
        Objects.equals(this.authType, accountManagementServiceSelector.authType) &&
        Objects.equals(this.includeTestAccount, accountManagementServiceSelector.includeTestAccount) &&
        Objects.equals(this.numberResults, accountManagementServiceSelector.numberResults) &&
        Objects.equals(this.startIndex, accountManagementServiceSelector.startIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountIds, accountStatuses, accountTypes, authType, includeTestAccount, numberResults, startIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountManagementServiceSelector {\n");
    sb.append("    accountIds: ").append(toIndentedString(accountIds)).append("\n");
    sb.append("    accountStatuses: ").append(toIndentedString(accountStatuses)).append("\n");
    sb.append("    accountTypes: ").append(toIndentedString(accountTypes)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    includeTestAccount: ").append(toIndentedString(includeTestAccount)).append("\n");
    sb.append("    numberResults: ").append(toIndentedString(numberResults)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

