/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.yahoo.adssearchapi.v4.model.AdGroupServiceAdRotationMode;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AdGroupServiceAdGroupAdRotationModeは、広告表示の最適化設定を表します。&lt;br&gt; ADDおよびSET時、このフィールドは省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AdGroupServiceAdGroupAdRotationMode describes Ad Rotation settings for optimizing and displaying ads.&lt;br&gt; This field is optional in ADD and SET operation.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">AdGroupServiceAdGroupAdRotationModeは、広告表示の最適化設定を表します。<br> ADDおよびSET時、このフィールドは省略可能となります。</div> <div lang=\"en\">AdGroupServiceAdGroupAdRotationMode describes Ad Rotation settings for optimizing and displaying ads.<br> This field is optional in ADD and SET operation.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class AdGroupServiceAdGroupAdRotationMode {
  public static final String SERIALIZED_NAME_AD_ROTATION_MODE = "adRotationMode";
  @SerializedName(SERIALIZED_NAME_AD_ROTATION_MODE)
  private AdGroupServiceAdRotationMode adRotationMode;


  public AdGroupServiceAdGroupAdRotationMode adRotationMode(AdGroupServiceAdRotationMode adRotationMode) {
    
    this.adRotationMode = adRotationMode;
    return this;
  }

   /**
   * Get adRotationMode
   * @return adRotationMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AdGroupServiceAdRotationMode getAdRotationMode() {
    return adRotationMode;
  }


  public void setAdRotationMode(AdGroupServiceAdRotationMode adRotationMode) {
    this.adRotationMode = adRotationMode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdGroupServiceAdGroupAdRotationMode adGroupServiceAdGroupAdRotationMode = (AdGroupServiceAdGroupAdRotationMode) o;
    return Objects.equals(this.adRotationMode, adGroupServiceAdGroupAdRotationMode.adRotationMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adRotationMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdGroupServiceAdGroupAdRotationMode {\n");
    sb.append("    adRotationMode: ").append(toIndentedString(adRotationMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

