/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.co.yahoo.adssearchapi.v4.model.BiddingStrategyServiceTargetCpaBiddingScheme;
import jp.co.yahoo.adssearchapi.v4.model.BiddingStrategyServiceTargetImpressionShareScheme;
import jp.co.yahoo.adssearchapi.v4.model.BiddingStrategyServiceTargetRoasBiddingScheme;
import jp.co.yahoo.adssearchapi.v4.model.BiddingStrategyServiceTargetSpendBiddingScheme;
import jp.co.yahoo.adssearchapi.v4.model.BiddingStrategyServiceType;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;BiddingStrategyServiceBiddingSchemeオブジェクトは、自動入札設定の詳細情報を表します。（BiddingStrategyService用のオブジェクトです。）&lt;br&gt; このフィールドは、ADD時は必須となり、SET時は省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;BiddingStrategyServiceBiddingScheme object displays the details of Auto Bidding setting. (This is for BiddingStrategyService)&lt;br&gt; This field is required in ADD operation, and will be optional in SET operation.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">BiddingStrategyServiceBiddingSchemeオブジェクトは、自動入札設定の詳細情報を表します。（BiddingStrategyService用のオブジェクトです。）<br> このフィールドは、ADD時は必須となり、SET時は省略可能となります。</div> <div lang=\"en\">BiddingStrategyServiceBiddingScheme object displays the details of Auto Bidding setting. (This is for BiddingStrategyService)<br> This field is required in ADD operation, and will be optional in SET operation.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class BiddingStrategyServiceBiddingScheme {
  public static final String SERIALIZED_NAME_TARGET_CPA_BIDDING_SCHEME = "targetCpaBiddingScheme";
  @SerializedName(SERIALIZED_NAME_TARGET_CPA_BIDDING_SCHEME)
  private BiddingStrategyServiceTargetCpaBiddingScheme targetCpaBiddingScheme;

  public static final String SERIALIZED_NAME_TARGET_ROAS_BIDDING_SCHEME = "targetRoasBiddingScheme";
  @SerializedName(SERIALIZED_NAME_TARGET_ROAS_BIDDING_SCHEME)
  private BiddingStrategyServiceTargetRoasBiddingScheme targetRoasBiddingScheme;

  public static final String SERIALIZED_NAME_TARGET_SPEND_BIDDING_SCHEME = "targetSpendBiddingScheme";
  @SerializedName(SERIALIZED_NAME_TARGET_SPEND_BIDDING_SCHEME)
  private BiddingStrategyServiceTargetSpendBiddingScheme targetSpendBiddingScheme;

  public static final String SERIALIZED_NAME_TARGET_IMPRESSION_SHARE_SCHEME = "targetImpressionShareScheme";
  @SerializedName(SERIALIZED_NAME_TARGET_IMPRESSION_SHARE_SCHEME)
  private BiddingStrategyServiceTargetImpressionShareScheme targetImpressionShareScheme;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private BiddingStrategyServiceType type;


  public BiddingStrategyServiceBiddingScheme targetCpaBiddingScheme(BiddingStrategyServiceTargetCpaBiddingScheme targetCpaBiddingScheme) {
    
    this.targetCpaBiddingScheme = targetCpaBiddingScheme;
    return this;
  }

   /**
   * Get targetCpaBiddingScheme
   * @return targetCpaBiddingScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BiddingStrategyServiceTargetCpaBiddingScheme getTargetCpaBiddingScheme() {
    return targetCpaBiddingScheme;
  }


  public void setTargetCpaBiddingScheme(BiddingStrategyServiceTargetCpaBiddingScheme targetCpaBiddingScheme) {
    this.targetCpaBiddingScheme = targetCpaBiddingScheme;
  }


  public BiddingStrategyServiceBiddingScheme targetRoasBiddingScheme(BiddingStrategyServiceTargetRoasBiddingScheme targetRoasBiddingScheme) {
    
    this.targetRoasBiddingScheme = targetRoasBiddingScheme;
    return this;
  }

   /**
   * Get targetRoasBiddingScheme
   * @return targetRoasBiddingScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BiddingStrategyServiceTargetRoasBiddingScheme getTargetRoasBiddingScheme() {
    return targetRoasBiddingScheme;
  }


  public void setTargetRoasBiddingScheme(BiddingStrategyServiceTargetRoasBiddingScheme targetRoasBiddingScheme) {
    this.targetRoasBiddingScheme = targetRoasBiddingScheme;
  }


  public BiddingStrategyServiceBiddingScheme targetSpendBiddingScheme(BiddingStrategyServiceTargetSpendBiddingScheme targetSpendBiddingScheme) {
    
    this.targetSpendBiddingScheme = targetSpendBiddingScheme;
    return this;
  }

   /**
   * Get targetSpendBiddingScheme
   * @return targetSpendBiddingScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BiddingStrategyServiceTargetSpendBiddingScheme getTargetSpendBiddingScheme() {
    return targetSpendBiddingScheme;
  }


  public void setTargetSpendBiddingScheme(BiddingStrategyServiceTargetSpendBiddingScheme targetSpendBiddingScheme) {
    this.targetSpendBiddingScheme = targetSpendBiddingScheme;
  }


  public BiddingStrategyServiceBiddingScheme targetImpressionShareScheme(BiddingStrategyServiceTargetImpressionShareScheme targetImpressionShareScheme) {
    
    this.targetImpressionShareScheme = targetImpressionShareScheme;
    return this;
  }

   /**
   * Get targetImpressionShareScheme
   * @return targetImpressionShareScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BiddingStrategyServiceTargetImpressionShareScheme getTargetImpressionShareScheme() {
    return targetImpressionShareScheme;
  }


  public void setTargetImpressionShareScheme(BiddingStrategyServiceTargetImpressionShareScheme targetImpressionShareScheme) {
    this.targetImpressionShareScheme = targetImpressionShareScheme;
  }


  public BiddingStrategyServiceBiddingScheme type(BiddingStrategyServiceType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BiddingStrategyServiceType getType() {
    return type;
  }


  public void setType(BiddingStrategyServiceType type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BiddingStrategyServiceBiddingScheme biddingStrategyServiceBiddingScheme = (BiddingStrategyServiceBiddingScheme) o;
    return Objects.equals(this.targetCpaBiddingScheme, biddingStrategyServiceBiddingScheme.targetCpaBiddingScheme) &&
        Objects.equals(this.targetRoasBiddingScheme, biddingStrategyServiceBiddingScheme.targetRoasBiddingScheme) &&
        Objects.equals(this.targetSpendBiddingScheme, biddingStrategyServiceBiddingScheme.targetSpendBiddingScheme) &&
        Objects.equals(this.targetImpressionShareScheme, biddingStrategyServiceBiddingScheme.targetImpressionShareScheme) &&
        Objects.equals(this.type, biddingStrategyServiceBiddingScheme.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetCpaBiddingScheme, targetRoasBiddingScheme, targetSpendBiddingScheme, targetImpressionShareScheme, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BiddingStrategyServiceBiddingScheme {\n");
    sb.append("    targetCpaBiddingScheme: ").append(toIndentedString(targetCpaBiddingScheme)).append("\n");
    sb.append("    targetRoasBiddingScheme: ").append(toIndentedString(targetRoasBiddingScheme)).append("\n");
    sb.append("    targetSpendBiddingScheme: ").append(toIndentedString(targetSpendBiddingScheme)).append("\n");
    sb.append("    targetImpressionShareScheme: ").append(toIndentedString(targetImpressionShareScheme)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

