/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;CampaignWebpageServiceWebpageOperatorは、URLの条件種別です。&lt;br&gt; このフィールドは、typeがURLの場合のみ指定できます。&lt;br&gt; operatorにEQUALSを指定する場合は、conditionsに1件のみ指定できます。&lt;br&gt; また、このフィールドはSETおよびREMOVE時に無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;CampaignWebpageServiceWebpageOperator is a condition type of URL. &lt;br&gt;  This field can be specified only if the type is URL.&lt;br&gt;  If you specified EQUALS in operator, you can specify only one value in condition. &lt;br&gt; This field will be ignored in SET and REMOVE operation.&lt;/div&gt; &lt;dl class&#x3D;term&gt;   &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;CONTAINS&lt;/dt&gt;   &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;指定の値を含みます。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Contains the selected value.&lt;/span&gt;&lt;/dd&gt;   &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;EQUALS&lt;/dt&gt;   &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;指定の値と一致します。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Equal to selected value.&lt;/span&gt;&lt;/dd&gt;   &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;UNKNOWN&lt;/dt&gt;   &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value&lt;/span&gt;&lt;/dd&gt; &lt;/dl&gt; 
 */
@JsonAdapter(CampaignWebpageServiceWebpageOperator.Adapter.class)
public enum CampaignWebpageServiceWebpageOperator {
  
  CONTAINS("CONTAINS"),
  
  EQUALS("EQUALS"),
  
  UNKNOWN("UNKNOWN");

  private String value;

  CampaignWebpageServiceWebpageOperator(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CampaignWebpageServiceWebpageOperator fromValue(String value) {
    for (CampaignWebpageServiceWebpageOperator b : CampaignWebpageServiceWebpageOperator.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CampaignWebpageServiceWebpageOperator> {
    @Override
    public void write(final JsonWriter jsonWriter, final CampaignWebpageServiceWebpageOperator enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CampaignWebpageServiceWebpageOperator read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CampaignWebpageServiceWebpageOperator.fromValue(value);
    }
  }
}

