/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;DictionaryServiceAppLinkVendor オブジェクトは、 アプリ計測ベンダー情報を格納するコンテナです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;DictionaryServiceAppLinkVendor object is a container that stores App measurement vendor information.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">DictionaryServiceAppLinkVendor オブジェクトは、 アプリ計測ベンダー情報を格納するコンテナです。</div> <div lang=\"en\">DictionaryServiceAppLinkVendor object is a container that stores App measurement vendor information.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class DictionaryServiceAppLinkVendor {
  public static final String SERIALIZED_NAME_APP_VENDOR_ID = "appVendorId";
  @SerializedName(SERIALIZED_NAME_APP_VENDOR_ID)
  private String appVendorId;

  public static final String SERIALIZED_NAME_APP_VENDOR_NAME_JA = "appVendorNameJa";
  @SerializedName(SERIALIZED_NAME_APP_VENDOR_NAME_JA)
  private String appVendorNameJa;

  public static final String SERIALIZED_NAME_APP_VENDOR_NAME_EN = "appVendorNameEn";
  @SerializedName(SERIALIZED_NAME_APP_VENDOR_NAME_EN)
  private String appVendorNameEn;


  public DictionaryServiceAppLinkVendor appVendorId(String appVendorId) {
    
    this.appVendorId = appVendorId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アプリ計測ベンダーIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;App Vendor ID.&lt;/div&gt; 
   * @return appVendorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">アプリ計測ベンダーIDです。</div> <div lang=\"en\">App Vendor ID.</div> ")

  public String getAppVendorId() {
    return appVendorId;
  }


  public void setAppVendorId(String appVendorId) {
    this.appVendorId = appVendorId;
  }


  public DictionaryServiceAppLinkVendor appVendorNameJa(String appVendorNameJa) {
    
    this.appVendorNameJa = appVendorNameJa;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アプリ計測ベンダー名（日本語）です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;App Vendor Name in Japanese.&lt;/div&gt; 
   * @return appVendorNameJa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">アプリ計測ベンダー名（日本語）です。</div> <div lang=\"en\">App Vendor Name in Japanese.</div> ")

  public String getAppVendorNameJa() {
    return appVendorNameJa;
  }


  public void setAppVendorNameJa(String appVendorNameJa) {
    this.appVendorNameJa = appVendorNameJa;
  }


  public DictionaryServiceAppLinkVendor appVendorNameEn(String appVendorNameEn) {
    
    this.appVendorNameEn = appVendorNameEn;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アプリ計測ベンダー名（英語）です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;App Vendor Name in English.&lt;/div&gt; 
   * @return appVendorNameEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">アプリ計測ベンダー名（英語）です。</div> <div lang=\"en\">App Vendor Name in English.</div> ")

  public String getAppVendorNameEn() {
    return appVendorNameEn;
  }


  public void setAppVendorNameEn(String appVendorNameEn) {
    this.appVendorNameEn = appVendorNameEn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DictionaryServiceAppLinkVendor dictionaryServiceAppLinkVendor = (DictionaryServiceAppLinkVendor) o;
    return Objects.equals(this.appVendorId, dictionaryServiceAppLinkVendor.appVendorId) &&
        Objects.equals(this.appVendorNameJa, dictionaryServiceAppLinkVendor.appVendorNameJa) &&
        Objects.equals(this.appVendorNameEn, dictionaryServiceAppLinkVendor.appVendorNameEn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appVendorId, appVendorNameJa, appVendorNameEn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DictionaryServiceAppLinkVendor {\n");
    sb.append("    appVendorId: ").append(toIndentedString(appVendorId)).append("\n");
    sb.append("    appVendorNameJa: ").append(toIndentedString(appVendorNameJa)).append("\n");
    sb.append("    appVendorNameEn: ").append(toIndentedString(appVendorNameEn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

