/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v4.model.KeywordForecastMetricsServiceKeywordPlanAdGroup;
import jp.co.yahoo.adssearchapi.v4.model.KeywordForecastMetricsServiceKeywordPlanNetwork;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;KeywordForecastMetricsServiceKeywordPlanCampaign オブジェクトは、見積もりリクエストを格納します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;KeywordForecastMetricsServiceKeywordPlanCampaign object is a container for the estimate request.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">KeywordForecastMetricsServiceKeywordPlanCampaign オブジェクトは、見積もりリクエストを格納します。</div> <div lang=\"en\">KeywordForecastMetricsServiceKeywordPlanCampaign object is a container for the estimate request.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class KeywordForecastMetricsServiceKeywordPlanCampaign {
  public static final String SERIALIZED_NAME_KEYWORD_PLAN_NETWORK = "keywordPlanNetwork";
  @SerializedName(SERIALIZED_NAME_KEYWORD_PLAN_NETWORK)
  private KeywordForecastMetricsServiceKeywordPlanNetwork keywordPlanNetwork;

  public static final String SERIALIZED_NAME_MAX_CPC = "maxCpc";
  @SerializedName(SERIALIZED_NAME_MAX_CPC)
  private Long maxCpc;

  public static final String SERIALIZED_NAME_GEO_TARGETS = "geoTargets";
  @SerializedName(SERIALIZED_NAME_GEO_TARGETS)
  private List<String> geoTargets = null;

  public static final String SERIALIZED_NAME_KEYWORD_PLAN_AD_GROUP = "keywordPlanAdGroup";
  @SerializedName(SERIALIZED_NAME_KEYWORD_PLAN_AD_GROUP)
  private KeywordForecastMetricsServiceKeywordPlanAdGroup keywordPlanAdGroup;


  public KeywordForecastMetricsServiceKeywordPlanCampaign keywordPlanNetwork(KeywordForecastMetricsServiceKeywordPlanNetwork keywordPlanNetwork) {
    
    this.keywordPlanNetwork = keywordPlanNetwork;
    return this;
  }

   /**
   * Get keywordPlanNetwork
   * @return keywordPlanNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KeywordForecastMetricsServiceKeywordPlanNetwork getKeywordPlanNetwork() {
    return keywordPlanNetwork;
  }


  public void setKeywordPlanNetwork(KeywordForecastMetricsServiceKeywordPlanNetwork keywordPlanNetwork) {
    this.keywordPlanNetwork = keywordPlanNetwork;
  }


  public KeywordForecastMetricsServiceKeywordPlanCampaign maxCpc(Long maxCpc) {
    
    this.maxCpc = maxCpc;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;最大クリック単価です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Maximum CPC.&lt;/div&gt; 
   * @return maxCpc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "<div lang=\"ja\">最大クリック単価です。</div> <div lang=\"en\">Maximum CPC.</div> ")

  public Long getMaxCpc() {
    return maxCpc;
  }


  public void setMaxCpc(Long maxCpc) {
    this.maxCpc = maxCpc;
  }


  public KeywordForecastMetricsServiceKeywordPlanCampaign geoTargets(List<String> geoTargets) {
    
    this.geoTargets = geoTargets;
    return this;
  }

  public KeywordForecastMetricsServiceKeywordPlanCampaign addGeoTargetsItem(String geoTargetsItem) {
    if (this.geoTargets == null) {
      this.geoTargets = new ArrayList<String>();
    }
    this.geoTargets.add(geoTargetsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;地域情報です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Area information.&lt;/div&gt; 
   * @return geoTargets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">地域情報です。</div> <div lang=\"en\">Area information.</div> ")

  public List<String> getGeoTargets() {
    return geoTargets;
  }


  public void setGeoTargets(List<String> geoTargets) {
    this.geoTargets = geoTargets;
  }


  public KeywordForecastMetricsServiceKeywordPlanCampaign keywordPlanAdGroup(KeywordForecastMetricsServiceKeywordPlanAdGroup keywordPlanAdGroup) {
    
    this.keywordPlanAdGroup = keywordPlanAdGroup;
    return this;
  }

   /**
   * Get keywordPlanAdGroup
   * @return keywordPlanAdGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public KeywordForecastMetricsServiceKeywordPlanAdGroup getKeywordPlanAdGroup() {
    return keywordPlanAdGroup;
  }


  public void setKeywordPlanAdGroup(KeywordForecastMetricsServiceKeywordPlanAdGroup keywordPlanAdGroup) {
    this.keywordPlanAdGroup = keywordPlanAdGroup;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeywordForecastMetricsServiceKeywordPlanCampaign keywordForecastMetricsServiceKeywordPlanCampaign = (KeywordForecastMetricsServiceKeywordPlanCampaign) o;
    return Objects.equals(this.keywordPlanNetwork, keywordForecastMetricsServiceKeywordPlanCampaign.keywordPlanNetwork) &&
        Objects.equals(this.maxCpc, keywordForecastMetricsServiceKeywordPlanCampaign.maxCpc) &&
        Objects.equals(this.geoTargets, keywordForecastMetricsServiceKeywordPlanCampaign.geoTargets) &&
        Objects.equals(this.keywordPlanAdGroup, keywordForecastMetricsServiceKeywordPlanCampaign.keywordPlanAdGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keywordPlanNetwork, maxCpc, geoTargets, keywordPlanAdGroup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeywordForecastMetricsServiceKeywordPlanCampaign {\n");
    sb.append("    keywordPlanNetwork: ").append(toIndentedString(keywordPlanNetwork)).append("\n");
    sb.append("    maxCpc: ").append(toIndentedString(maxCpc)).append("\n");
    sb.append("    geoTargets: ").append(toIndentedString(geoTargets)).append("\n");
    sb.append("    keywordPlanAdGroup: ").append(toIndentedString(keywordPlanAdGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

