/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;KeywordEstimatorServiceEstimateResult オブジェクトは、見積もりリクエストを格納するコンテナです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;EstimateKeyword object is a container for the estimate request.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">KeywordEstimatorServiceEstimateResult オブジェクトは、見積もりリクエストを格納するコンテナです。</div> <div lang=\"en\">EstimateKeyword object is a container for the estimate request.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class KeywordEstimatorServiceEstimateResult {
  public static final String SERIALIZED_NAME_CLICKS = "clicks";
  @SerializedName(SERIALIZED_NAME_CLICKS)
  private Double clicks;

  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  private Double cost;

  public static final String SERIALIZED_NAME_CPC = "cpc";
  @SerializedName(SERIALIZED_NAME_CPC)
  private Double cpc;

  public static final String SERIALIZED_NAME_CTR = "ctr";
  @SerializedName(SERIALIZED_NAME_CTR)
  private Double ctr;

  public static final String SERIALIZED_NAME_IMPRESSIONS = "impressions";
  @SerializedName(SERIALIZED_NAME_IMPRESSIONS)
  private Double impressions;

  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  private Double rank;


  public KeywordEstimatorServiceEstimateResult clicks(Double clicks) {
    
    this.clicks = clicks;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;1日あたりのクリック数です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Number of clicks per day&lt;/div&gt; 
   * @return clicks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">1日あたりのクリック数です。</div> <div lang=\"en\">Number of clicks per day</div> ")

  public Double getClicks() {
    return clicks;
  }


  public void setClicks(Double clicks) {
    this.clicks = clicks;
  }


  public KeywordEstimatorServiceEstimateResult cost(Double cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;1日あたりの推定合計費用です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Total amount of CPC cost per day&lt;/div&gt; 
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">1日あたりの推定合計費用です。</div> <div lang=\"en\">Total amount of CPC cost per day</div> ")

  public Double getCost() {
    return cost;
  }


  public void setCost(Double cost) {
    this.cost = cost;
  }


  public KeywordEstimatorServiceEstimateResult cpc(Double cpc) {
    
    this.cpc = cpc;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;推定平均クリック単価です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Assumed average CPC&lt;/div&gt; 
   * @return cpc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">推定平均クリック単価です。</div> <div lang=\"en\">Assumed average CPC</div> ")

  public Double getCpc() {
    return cpc;
  }


  public void setCpc(Double cpc) {
    this.cpc = cpc;
  }


  public KeywordEstimatorServiceEstimateResult ctr(Double ctr) {
    
    this.ctr = ctr;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;推定CTRです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Estimation of CTR.&lt;/div&gt; 
   * @return ctr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">推定CTRです。</div> <div lang=\"en\">Estimation of CTR.</div> ")

  public Double getCtr() {
    return ctr;
  }


  public void setCtr(Double ctr) {
    this.ctr = ctr;
  }


  public KeywordEstimatorServiceEstimateResult impressions(Double impressions) {
    
    this.impressions = impressions;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;1日当たりの推定インプレッション数です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Estimation of impression per day.&lt;/div&gt; 
   * @return impressions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">1日当たりの推定インプレッション数です。</div> <div lang=\"en\">Estimation of impression per day.</div> ")

  public Double getImpressions() {
    return impressions;
  }


  public void setImpressions(Double impressions) {
    this.impressions = impressions;
  }


  public KeywordEstimatorServiceEstimateResult rank(Double rank) {
    
    this.rank = rank;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;推定平均掲載順位です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Assumed average display rank&lt;/div&gt; 
   * @return rank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">推定平均掲載順位です。</div> <div lang=\"en\">Assumed average display rank</div> ")

  public Double getRank() {
    return rank;
  }


  public void setRank(Double rank) {
    this.rank = rank;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeywordEstimatorServiceEstimateResult keywordEstimatorServiceEstimateResult = (KeywordEstimatorServiceEstimateResult) o;
    return Objects.equals(this.clicks, keywordEstimatorServiceEstimateResult.clicks) &&
        Objects.equals(this.cost, keywordEstimatorServiceEstimateResult.cost) &&
        Objects.equals(this.cpc, keywordEstimatorServiceEstimateResult.cpc) &&
        Objects.equals(this.ctr, keywordEstimatorServiceEstimateResult.ctr) &&
        Objects.equals(this.impressions, keywordEstimatorServiceEstimateResult.impressions) &&
        Objects.equals(this.rank, keywordEstimatorServiceEstimateResult.rank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clicks, cost, cpc, ctr, impressions, rank);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeywordEstimatorServiceEstimateResult {\n");
    sb.append("    clicks: ").append(toIndentedString(clicks)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    cpc: ").append(toIndentedString(cpc)).append("\n");
    sb.append("    ctr: ").append(toIndentedString(ctr)).append("\n");
    sb.append("    impressions: ").append(toIndentedString(impressions)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

