/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;OfflineConversionServiceSortTypeは、ソート条件を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;OfflineConversionServiceSortType is a sort condition type.&lt;/div&gt; &lt;dl class&#x3D;term&gt; &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;ASC&lt;/dt&gt; &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;昇順にソートされます。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Sort in ascending order.&lt;/span&gt;&lt;/dd&gt; &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;DESC&lt;/dt&gt; &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;降順にソートされます。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Sort in descending order.&lt;/span&gt;&lt;/dd&gt; &lt;dt class&#x3D;\&quot;term__item\&quot;&gt;UNKNOWN&lt;/dt&gt; &lt;dd class&#x3D;\&quot;term__desc\&quot;&gt;&lt;span lang&#x3D;\&quot;ja\&quot;&gt;未知の値です。&lt;/span&gt;&lt;span lang&#x3D;\&quot;en\&quot;&gt;Unknown Value.&lt;/span&gt;&lt;/dd&gt; &lt;/dl&gt;
 */
@JsonAdapter(OfflineConversionServiceSortType.Adapter.class)
public enum OfflineConversionServiceSortType {
  
  ASC("ASC"),
  
  DESC("DESC"),
  
  UNKNOWN("UNKNOWN");

  private String value;

  OfflineConversionServiceSortType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OfflineConversionServiceSortType fromValue(String value) {
    for (OfflineConversionServiceSortType b : OfflineConversionServiceSortType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OfflineConversionServiceSortType> {
    @Override
    public void write(final JsonWriter jsonWriter, final OfflineConversionServiceSortType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OfflineConversionServiceSortType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OfflineConversionServiceSortType.fromValue(value);
    }
  }
}

