/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v4/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v4.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;PageFeedItemServiceReviewSummaryオブジェクトは、ページフィードアイテムの審査成績、状況サマリーを格納します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;PageFeedItemServiceReviewSummary object retains the examination results of the page feed item, the situation summary acquisition result.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">PageFeedItemServiceReviewSummaryオブジェクトは、ページフィードアイテムの審査成績、状況サマリーを格納します。</div> <div lang=\"en\">PageFeedItemServiceReviewSummary object retains the examination results of the page feed item, the situation summary acquisition result.</div> ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-15T15:50:35.264006+01:00[Europe/Paris]")
public class PageFeedItemServiceReviewSummary {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private Long accountId;

  public static final String SERIALIZED_NAME_APPROVED_COUNT = "approvedCount";
  @SerializedName(SERIALIZED_NAME_APPROVED_COUNT)
  private Long approvedCount;

  public static final String SERIALIZED_NAME_APPROVED_WITH_REVIEW_COUNT = "approvedWithReviewCount";
  @SerializedName(SERIALIZED_NAME_APPROVED_WITH_REVIEW_COUNT)
  private Long approvedWithReviewCount;

  public static final String SERIALIZED_NAME_ENTITY_COUNT = "entityCount";
  @SerializedName(SERIALIZED_NAME_ENTITY_COUNT)
  private Long entityCount;

  public static final String SERIALIZED_NAME_FEED_ID = "feedId";
  @SerializedName(SERIALIZED_NAME_FEED_ID)
  private Long feedId;

  public static final String SERIALIZED_NAME_POST_DISAPPROVED_COUNT = "postDisapprovedCount";
  @SerializedName(SERIALIZED_NAME_POST_DISAPPROVED_COUNT)
  private Long postDisapprovedCount;

  public static final String SERIALIZED_NAME_PRE_DISAPPROVED_COUNT = "preDisapprovedCount";
  @SerializedName(SERIALIZED_NAME_PRE_DISAPPROVED_COUNT)
  private Long preDisapprovedCount;

  public static final String SERIALIZED_NAME_REVIEW_COUNT = "reviewCount";
  @SerializedName(SERIALIZED_NAME_REVIEW_COUNT)
  private Long reviewCount;


  public PageFeedItemServiceReviewSummary accountId(Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウントID&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account ID&lt;/div&gt; 
   * @return accountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">アカウントID</div> <div lang=\"en\">Account ID</div> ")

  public Long getAccountId() {
    return accountId;
  }


  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }


  public PageFeedItemServiceReviewSummary approvedCount(Long approvedCount) {
    
    this.approvedCount = approvedCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;承認済みの件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Count of approved&lt;/div&gt; 
   * @return approvedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">承認済みの件数</div> <div lang=\"en\">Count of approved</div> ")

  public Long getApprovedCount() {
    return approvedCount;
  }


  public void setApprovedCount(Long approvedCount) {
    this.approvedCount = approvedCount;
  }


  public PageFeedItemServiceReviewSummary approvedWithReviewCount(Long approvedWithReviewCount) {
    
    this.approvedWithReviewCount = approvedWithReviewCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;編集内容審査中の件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Count of approved with review&lt;/div&gt; 
   * @return approvedWithReviewCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">編集内容審査中の件数</div> <div lang=\"en\">Count of approved with review</div> ")

  public Long getApprovedWithReviewCount() {
    return approvedWithReviewCount;
  }


  public void setApprovedWithReviewCount(Long approvedWithReviewCount) {
    this.approvedWithReviewCount = approvedWithReviewCount;
  }


  public PageFeedItemServiceReviewSummary entityCount(Long entityCount) {
    
    this.entityCount = entityCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;フィードフォルダ内にあるページフィードアイテムの総件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Total count of page feed item in feed folder&lt;/div&gt; 
   * @return entityCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">フィードフォルダ内にあるページフィードアイテムの総件数</div> <div lang=\"en\">Total count of page feed item in feed folder</div> ")

  public Long getEntityCount() {
    return entityCount;
  }


  public void setEntityCount(Long entityCount) {
    this.entityCount = entityCount;
  }


  public PageFeedItemServiceReviewSummary feedId(Long feedId) {
    
    this.feedId = feedId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;フィードID&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Feed ID&lt;/div&gt; 
   * @return feedId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">フィードID</div> <div lang=\"en\">Feed ID</div> ")

  public Long getFeedId() {
    return feedId;
  }


  public void setFeedId(Long feedId) {
    this.feedId = feedId;
  }


  public PageFeedItemServiceReviewSummary postDisapprovedCount(Long postDisapprovedCount) {
    
    this.postDisapprovedCount = postDisapprovedCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;配信停止の件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Count of distribution cancelled&lt;/div&gt; 
   * @return postDisapprovedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">配信停止の件数</div> <div lang=\"en\">Count of distribution cancelled</div> ")

  public Long getPostDisapprovedCount() {
    return postDisapprovedCount;
  }


  public void setPostDisapprovedCount(Long postDisapprovedCount) {
    this.postDisapprovedCount = postDisapprovedCount;
  }


  public PageFeedItemServiceReviewSummary preDisapprovedCount(Long preDisapprovedCount) {
    
    this.preDisapprovedCount = preDisapprovedCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;掲載不可の件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Count of disapproved&lt;/div&gt; 
   * @return preDisapprovedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">掲載不可の件数</div> <div lang=\"en\">Count of disapproved</div> ")

  public Long getPreDisapprovedCount() {
    return preDisapprovedCount;
  }


  public void setPreDisapprovedCount(Long preDisapprovedCount) {
    this.preDisapprovedCount = preDisapprovedCount;
  }


  public PageFeedItemServiceReviewSummary reviewCount(Long reviewCount) {
    
    this.reviewCount = reviewCount;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;審査中の件数&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Count of review&lt;/div&gt; 
   * @return reviewCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">審査中の件数</div> <div lang=\"en\">Count of review</div> ")

  public Long getReviewCount() {
    return reviewCount;
  }


  public void setReviewCount(Long reviewCount) {
    this.reviewCount = reviewCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageFeedItemServiceReviewSummary pageFeedItemServiceReviewSummary = (PageFeedItemServiceReviewSummary) o;
    return Objects.equals(this.accountId, pageFeedItemServiceReviewSummary.accountId) &&
        Objects.equals(this.approvedCount, pageFeedItemServiceReviewSummary.approvedCount) &&
        Objects.equals(this.approvedWithReviewCount, pageFeedItemServiceReviewSummary.approvedWithReviewCount) &&
        Objects.equals(this.entityCount, pageFeedItemServiceReviewSummary.entityCount) &&
        Objects.equals(this.feedId, pageFeedItemServiceReviewSummary.feedId) &&
        Objects.equals(this.postDisapprovedCount, pageFeedItemServiceReviewSummary.postDisapprovedCount) &&
        Objects.equals(this.preDisapprovedCount, pageFeedItemServiceReviewSummary.preDisapprovedCount) &&
        Objects.equals(this.reviewCount, pageFeedItemServiceReviewSummary.reviewCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, approvedCount, approvedWithReviewCount, entityCount, feedId, postDisapprovedCount, preDisapprovedCount, reviewCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageFeedItemServiceReviewSummary {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    approvedCount: ").append(toIndentedString(approvedCount)).append("\n");
    sb.append("    approvedWithReviewCount: ").append(toIndentedString(approvedWithReviewCount)).append("\n");
    sb.append("    entityCount: ").append(toIndentedString(entityCount)).append("\n");
    sb.append("    feedId: ").append(toIndentedString(feedId)).append("\n");
    sb.append("    postDisapprovedCount: ").append(toIndentedString(postDisapprovedCount)).append("\n");
    sb.append("    preDisapprovedCount: ").append(toIndentedString(preDisapprovedCount)).append("\n");
    sb.append("    reviewCount: ").append(toIndentedString(reviewCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

